version: '3.8'
# Docker Compose file to set up Jenkins CI environment with Docker-in-Docker (DinD)

services:
  docker:
    # DinD service to allow Jenkins to run Docker commands
    image: docker:dind
    privileged: true   # Required for Docker-in-Docker
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs    # Secure Docker with TLS
    volumes:
      - docker-certs:/certs/client   # Shared TLS certs with Jenkins
      - docker-data:/var/lib/docker   # Persistent Docker layer cache
    networks:
      - jenkins

  jenkins:
    # Jenkins LTS image
    image: jenkins/jenkins:lts
    user: root    # Required to install plugins and use Docker socket
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000"   # For Jenkins agents
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home   # Jenkins home directory
      - docker-certs:/certs/client:ro    # Mount certs from DinD
    networks:
      - jenkins
# Named volumes for persistence
volumes:
  jenkins-data:
  docker-certs:
  docker-data:
# Custom network for communication between Jenkins and Docker

networks:
  jenkins:
